### ISSUE TITLE
Make more pretty

### ISSUE THREAD

**Issue by augustoroman** [sillypantscoder/pygame_platformer_2#10]
Maybe add textures for blocks, add background image/texture with parallax, add sprites (and maybe shadows onto the background).

**Comment by sillypantscoder** [comment]
Already [added textures](https://github.com/sillypantscoder/pygame_platformer_2/commit/3c837562df06a6e5226ffcb86054db45dc9c9e04), will probably add block textures soon as well.

**Comment by sillypantscoder** [comment]
Block textures were somewhat forgotten about with the addition of blocks.json, but they will be back!

**Comment by sillypantscoder** [comment]
[Re-added block textures](https://github.com/sillypantscoder/pygame_platformer_2/commit/f2a3141576b16d747f9b789c03650ca95d2f0ecd), and added textures for sand and flowing water. Will add sand entity textures soon. Not planning to add background.
