### ISSUE TITLE
Go faster

### ISSUE THREAD

**Issue by augustoroman** [sillypantscoder/pygame_platformer_2#12]
The game slows down sometimes, for no apparent reason. It would be nice if that didn't happen. Apparently related to the off-screen entities, but maybe that shouldn't matter?

Some possible solutions:
- Automatically skip the ticking of off-screen entities when the framerate drops
- Tick only some of the off-screen entities, e.g. the first half on one frame and the second half on the other frames. The fraction can be scaled according to the framerate.

**Comment by sillypantscoder** [comment]
[Fixed](https://github.com/sillypantscoder/pygame_platformer_2/commit/79cd95893d986cd31aa9fed46059ff47454a7d50)
